//! BYKC module split into API, public data types, and internal helpers.
//! Actually this part is kinda complicated
//! so i don't have much time and energy to review it carefully
//! most of codes is generated by AI, so i will determine this part as **experimental**
//! until i review this module and refractor it
//! --------------------------------------
//! **!TODO: Need Review**

mod api;
mod helpers;
mod raw;
mod types;

pub use api::BykcApi;
pub(crate) use helpers::can_deselect_bykc_course;
pub use types::{BykcChosenCourse, BykcCourse, BykcCourseDetail};
