//! Machine-readable description of the CLI, for automated callers.
//!
//! Why:
//! An agent driving this tool needs three things that `--help` does not state
//! reliably: which commands change real state, which require explicit
//! confirmation, and what the arguments are in a parseable form. Scraping help
//! text is brittle and version-dependent, so the same metadata is emitted as
//! JSON here.
//!
//! How:
//! Arguments come from clap's own introspection, so they cannot drift from the
//! real parser. The write/confirm classification does not come from clap, since
//! it is a property of what the command does rather than how it is declared; it
//! is stated once in [`classify`].

use anyhow::Result;
use clap::{Arg, CommandFactory};
use serde_json::{Value, json};

use super::args::Cli;

/// What a command does to the world outside this process.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]

enum Effect {
    /// Reads data only.
    Read,
    /// Changes state on a remote service.
    Write,
    /// Changes state and cannot be undone through this tool.
    WriteIrreversible,
}

impl Effect {
    fn as_str(self) -> &'static str {

        match self {
            Self::Read => "read",
            Self::Write => "write",
            Self::WriteIrreversible => "write_irreversible",
        }
    }
}

/// Classifies one subcommand.
///
/// Why:
/// This is the piece an automated caller cannot infer: a command that writes
/// looks exactly like one that reads until it runs. Stating it here, once,
/// keeps the schema honest about which calls are safe to retry.
///
/// How:
/// Irreversible means the action cannot be undone from this tool at all:
/// clock-in records and evaluations have no delete command, whereas a booking
/// or reservation can be cancelled.

fn classify(name: &str) -> Effect {

    match name {
        // Pure reads.
        "list-today" | "doctor" | "notify" | "venues" | "venue-slots" | "venue-orders"
        | "seats" | "seat-orders" | "clockin" | "eval" | "today" | "exams" | "grades"
        | "classrooms" | "tasks" | "schedule-export" | "schedule-diff" | "schema"
        | "autologin-status" => Effect::Read,

        // Can be undone through the tool: a reservation or booking is
        // cancellable with —x or --cancel.
        "venue-reserve" | "seat-book" | "sign" | "plan" => Effect::Write,

        // Nothing undoes these.
        "clockin-submit" | "eval-submit" => Effect::WriteIrreversible,

        // Scheduler installation is reversible but touches the host system.
        "install-autologin" | "uninstall-autologin" => Effect::Write,

        _ => Effect::Read,
    }
}

/// Builds the schema document.

pub(crate) fn schema_json() -> Result<Value> {

    let command = Cli::command();

    let mut commands = Vec::new();

    // clap's introspection gives the subcommands; the classification is layered
    // on from `classify`.
    for subcommand in command.get_subcommands() {

        let name = subcommand.get_name().to_string();

        // clap includes the implicit `help` subcommand; it is not part of the
        // tool's own surface.
        if name == "help" {

            continue;
        }

        let effect = classify(&name);

        let arguments: Vec<Value> = subcommand
            .get_arguments()
            // Positional args are not used by this CLI, and help/version are
            // generated by clap.
            .filter(|arg| arg.get_id() != "help" && arg.get_id() != "version")
            .map(describe_argument)
            .collect();

        // Read from the parser rather than assumed: a command that writes but
        // has no confirmation flag must not claim one, or a caller will pass a
        // flag that does not exist.
        let confirm_flag = arguments
            .iter()
            .find(|argument| argument["name"] == "yes")
            .and_then(|argument| argument["long"].as_str())
            .map(str::to_string);

        commands.push(json!({
            "name": name,
            "summary": subcommand.get_about().map(|about| about.to_string()),
            "effect": effect.as_str(),
            "confirmation_flag": confirm_flag,
            "supports_json": arguments.iter().any(|argument| argument["name"] == "json"),
            "arguments": arguments,
        }));
    }

    // Execution order matters for a caller: reads that establish a session
    // should come first, and writes last.
    commands.sort_by_key(|entry| {

        match entry["effect"].as_str() {
            Some("read") => 0,
            Some("write") => 1,
            _ => 2,
        }
    });

    Ok(json!({
        "tool": "iclass_buaa_tui",
        "version": env!("CARGO_PKG_VERSION"),
        "summary": "北航课程与校园服务终端工具：课表、成绩、作业、签到、研讨室、图书馆、打卡、评教。",
        "conventions": {
            "json": "除了 schema 本身，所有命令都支持 --json 输出结构化结果。",
            "confirmation": "标为写操作的命令在没有确认标志时只做预览，输出 submitted=false；加上确认标志才会真正执行。",
            "exit_codes": {
                "0": "成功",
                "1": "失败（未登录、参数错误、上游拒绝等）",
            },
            "session": "大多数命令会自动登录；需要统一认证凭据时读取配置文件。先用 doctor 检查连通性。",
        },
        "commands": commands,
    }))
}

/// Describes one clap argument.

fn describe_argument(arg: &Arg) -> Value {

    let takes_value = arg.get_action().takes_values();

    let possible_values: Vec<String> = arg
        .get_possible_values()
        .iter()
        .map(|value| value.get_name().to_string())
        .collect();

    // A flag is boolean when it takes no value; that distinction matters to a
    // caller passing arguments programmatically.
    let kind = if takes_value { "option" } else { "flag" };

    json!({
        "name": arg.get_id().to_string(),
        "long": arg.get_long().map(|long| format!("--{long}")),
        "kind": kind,
        "required": arg.is_required_set(),
        "help": arg.get_help().map(|help| help.to_string()),
        "default": arg.get_default_values().first().map(|value| value.to_string_lossy().to_string()),
        "possible_values": possible_values,
        "repeats": arg.get_action().takes_values() && arg.get_num_args().is_some_and(|range| range.max_values() > 1),
    })
}

/// Handles `schema`.
///
/// How:
/// JSON is the only useful form for this command, so it always prints JSON;
/// `--json` is accepted for symmetry with the rest of the CLI.

pub(crate) fn schema_command() -> Result<()> {

    println!("{}", serde_json::to_string_pretty(&schema_json()?)?);

    Ok(())
}

#[cfg(test)]

mod tests {

    use super::{Effect, classify, schema_json};

    #[test]

    fn writes_are_classified_and_reads_are_not() {

        assert_eq!(classify("venues"), Effect::Read);

        assert_eq!(classify("grades"), Effect::Read);

        assert_eq!(classify("venue-reserve"), Effect::Write);

        assert_eq!(classify("seat-book"), Effect::Write);

        // These cannot be undone at all, which is a different promise from
        // "changes state".
        assert_eq!(classify("clockin-submit"), Effect::WriteIrreversible);

        assert_eq!(classify("eval-submit"), Effect::WriteIrreversible);
    }

    #[test]

    fn reads_and_writes_are_distinguishable() {

        assert_eq!(Effect::Read.as_str(), "read");

        assert_ne!(Effect::Write.as_str(), Effect::Read.as_str());
    }

    #[test]

    fn schema_lists_every_command_with_its_effect() {

        let schema = schema_json().expect("应能生成 schema");

        let commands = schema["commands"].as_array().expect("应有 commands 数组");

        assert!(!commands.is_empty());

        // The implicit clap `help` subcommand is not part of the tool's surface.
        assert!(
            !commands.iter().any(|entry| entry["name"] == "help"),
            "不应包含 clap 自动生成的 help"
        );

        // Every entry carries the fields a caller needs.
        for entry in commands {

            assert!(entry["name"].is_string());

            assert!(entry["effect"].is_string());

            assert!(entry["confirmation_flag"].is_string() || entry["confirmation_flag"].is_null());
        }
    }

    #[test]

    fn destructive_commands_are_marked_as_such() {

        let schema = schema_json().expect("应能生成 schema");

        let commands = schema["commands"].as_array().expect("应有 commands 数组");

        for name in ["clockin-submit", "eval-submit"] {

            let entry = commands
                .iter()
                .find(|entry| entry["name"] == name)
                .unwrap_or_else(|| panic!("schema 缺少 {name}"));

            assert_eq!(entry["effect"], "write_irreversible");

            // These must actually accept the flag the schema tells callers to pass.
            assert_eq!(entry["confirmation_flag"], "--yes");
        }
    }

    #[test]

    fn arguments_come_from_clap_so_they_cannot_drift() {

        let schema = schema_json().expect("应能生成 schema");

        let commands = schema["commands"].as_array().expect("应有 commands 数组");

        let venues = commands
            .iter()
            .find(|entry| entry["name"] == "venues")
            .expect("schema 应有 venues");

        let names: Vec<&str> = venues["arguments"]
            .as_array()
            .expect("应有 arguments")
            .iter()
            .filter_map(|argument| argument["name"].as_str())
            .collect();

        // The real parser has these; the schema must mirror it.
        for expected in ["config", "json", "debug_login"] {

            assert!(names.contains(&expected), "venues 缺少参数 {expected}");
        }

        assert_eq!(venues["supports_json"], true);
    }
}
